/** Bairros de Pimenta Bueno - RO para autocomplete padronizado. */
export const NEIGHBORHOODS = [
  'Centro',
  'Setor 01',
  'Setor 02',
  'Setor 03',
  'Setor 04',
  'Setor 05',
  'Setor 06',
  'Setor 07',
  'Setor 08',
  'Setor 09',
  'Setor 10',
  'Jardim Tropical',
  'Jardim das Palmeiras',
  'Jardim Primavera',
  'Jardim América',
  'Residencial Apuí',
  'Cohab',
  'Nova Pimenta',
  'Bairro dos Pioneiros',
  'Jardim Eldorado',
  'Jardim Paraíso',
  'Zona Rural',
]
